FROM envoyproxy/envoy:v1.32.0
COPY envoy/envoy.yaml /etc/envoy/envoy.yaml
EXPOSE 8080 8443 9901
ENTRYPOINT ["/usr/local/bin/envoy"]
CMD ["-c", "/etc/envoy/envoy.yaml", "--log-level", "warn", "--service-cluster", "api-gateway", "--service-node", "envoy-0", "--drain-time-s", "20"]
